#pragma once

#define TAPPING_TERM 200
#define LEADER_TIMEOUT 350

#define MK_VARIANT MK_TYPE_KINETIC

#define MK_KINETIC_MOUSE_MAXS 72
#define MK_KINETIC_MOUSE_ACCN 22
#define MK_KINETIC_MOUSE_FRIC 14
#define MK_KINETIC_MOUSE_DRAG 18

#define MK_KINETIC_WHEEL_MAXS 1
#define MK_KINETIC_WHEEL_ACCN 16

#define MS_J_MARGIN 0.1f
