SEND_STRING_ENABLE    = yes
NKRO_ENABLE           = yes
LEADER_ENABLE         = yes
MOUSEKEY_ENABLE       = yes
DIGITIZER_ENABLE      = yes

DYNAMIC_KEYMAP_ENABLE = no
SPACE_CADET_ENABLE    = no
AUDIO_ENABLE          = no
UNICODE_ENABLE        = no
SWAP_HANDS_ENABLE     = no

LTO_ENABLE = yes